attempted react-carousel-component
johndo-dev/m3-0321-code-solutions pull request #20
Opened 2021-04-03 10:12 UTC by johndo-dev

![F1](https://user-images.githubusercontent.com/67031107/113475398-51645800-942a-11eb-8a44-9095d48b43b5.gif)

2021-04-03 17:24 UTC, scbowler requested changes
Great job on this so far, a couple cleanup things needed. See below comments for details. Let me know if you have any questions.

2021-04-03 17:24 UTC, scbowler commented on react-carousel-component/src/carousel.jsx
> +    const slides = document.getElementsByClassName("slide");
You don't want to query the DOM when using React. A better solution here would be to use `this.props.items`, you can check the length of that array to determine the next index.

2021-04-03 17:24 UTC, scbowler commented on react-carousel-component/src/carousel.jsx
> +    }
This should be structured a little different by using else if statements so you don't have the extra setState call here on line 24.

```JSX
if (n >= slides.length) {
  ...
} else if (n < 0) {
  ...
} else {
  ...
}
```

2021-04-08 11:19 UTC, johndo-dev commented
![F1](https://user-images.githubusercontent.com/67031107/114017979-92d97680-9821-11eb-921e-4d45a2abcec4.gif)

2021-04-08 23:24 UTC, scbowler requested changes
Sooooo close, one more change. See below comment for details. Let me know if you have any questions.

2021-04-08 23:24 UTC, scbowler commented on react-carousel-component/src/carousel.jsx
> +    window.onload = this.slideShow
This is not the correct way to do this in React. Remember there are life cycle method in React components.

You want to call `this.slideShow()` from the `componentDidMount` method

2021-04-13 18:38 UTC, scbowler approved these changes
Great job! 👍

2021-04-15 08:47 UTC, merged