completed react-file-uploads
johndo-dev/m3-0321-code-solutions pull request #30
Opened 2021-04-17 20:54 UTC by johndo-dev

![image](https://user-images.githubusercontent.com/67031107/115126517-6ee60580-9f84-11eb-814f-0efc7447627c.png)
![F1](https://user-images.githubusercontent.com/67031107/115126518-71485f80-9f84-11eb-930a-eed81dffadd3.gif)

2021-04-17 20:58 UTC, scbowler requested changes
The React, client side, looks good. However looks like you missed the server side of the exercise.

2021-04-17 20:58 UTC, scbowler commented on react-file-uploads/server/index.js
> +   */
Looks like you missed the server side portion of the exercise.

2021-04-21 08:18 UTC, johndo-dev commented
![image](https://user-images.githubusercontent.com/67031107/115520947-843a8880-a23f-11eb-9f55-adb18d816f24.png)

2021-04-22 17:52 UTC, scbowler approved these changes
Looks good 👍 

One FYI comment below, no changes required.

2021-04-22 17:52 UTC, scbowler commented on react-file-uploads/server/index.js
> +      res.status(201).json(user);
Watch your variable names, this isn't a `user`. Something like `image` or something would be more appropriate.

2021-12-01 12:21 UTC, merged